### ISSUE TITLE
Ontology hierarchy bug fix

### ISSUE THREAD

**Issue by kdaveed** [RDFBones/RDFBones-O#104]
@zarquon42b @cuboideum 

Please check the branch nextTry. 
The problem was that the following ontology structure is a sort of overdefinition:

![screen shot 2017-03-08 at 13 03 27](https://cloud.githubusercontent.com/assets/7580884/23703321/a400fd08-03ff-11e7-8db7-d0734c7a5ffb.png)

But this way it works:

![screen shot 2017-03-08 at 13 03 44](https://cloud.githubusercontent.com/assets/7580884/23703330/ae219860-03ff-11e7-8652-912370e2d87f.png)

**Comment by kdaveed** [comment]
And currently we add only left or right bone organs anyway on the interface.

**Comment by cuboideum** [comment]
@zarquon42b has found out that even superordinate classes can be used, provided the hierarchies of subclasses of rdfbones:Completeness2StatesEntireBonyPartOfBoneOrgan and rdfbones:EntireBonyPartOfBoneOrgan match. I am working on bringing the completeness classes into that state.

**Comment by zarquon42b** [comment]
Yes, provided the inheritance is like this:
![a400fd08-03ff-11e7-8db7-d0734c7a5ffb](https://cloud.githubusercontent.com/assets/1515863/23722334/349bda3c-0445-11e7-89f8-75ac9dd3b255.png)
