### ISSUE TITLE
Categorical value specifications

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBones-O#112]
The OBI uses the concept of value specifications (*obo:OBI_0001933*) to model data estimations, simulations, targets and settings. Currently, there are classes representing specifications for categorical and scalar measurement data. While the use of scalar value specifications is quite straightforward, it is not quite clear how categorical value specifications (*obo:OBI_0001930*) are intended to work.

Class *obo:OBI_0001930* ('Categorical value specification') is defined as follows:

> A value specification that is specifies one category out of a fixed number of nominal categories

This implies that the value specification should specify one instance of *obo:OBI_0000963* ('Categorical label') among those which are appropriate for a certain categorical measurement datum (*obo:OBI_0000936*), defined by object property *obo:OBI_0000999* ('has category label').

The following graph illustrates my understanding of categorical value specifications in the OBI, using the example that is currently implemented, handedness.

![rdfbones-o_datainobi_categoricaldataspecification](https://cloud.githubusercontent.com/assets/8103073/26302480/a8d0b61e-3ee4-11e7-9644-c2f0c3949506.png)
**Figure:** Categorical value specifications according to the OBI (cf. [key to symbols in network graphs](https://github.com/RDFBones/RDFBones-O/wiki/Network-graph-legend)).

It is obvious that the categorical value specification is linked to the measurement value that is specified through the object property *obo:OBI_0001938* ('has value specification'). But how is it related to the categorical label that is to be the specified value ('left handed' in the example above)? The object property *obo:OBI_0000999* ('has category label') cannot be used, as its domain is limited to obo:OBI_0000938 ('categorical measurement datum'). The data property used for identifying the specified value of scalar value specifications, *obo:OBI_0001937* ('has specified value') is also not applicable, as it cannot be applied as an object property.

So it seems that an equivalent to *obo:OBI_0001937* ('has specified value') for categorical value specifications has to be introduced, unless it cannot be figured out how categorical value specifications are meant to reference one particular category label according to the OBI.

**Comment by cuboideum** [comment]
I propose to introduce an object property (*:hasSpecifiedCategoryLabel*), specifying categorical labels referenced by categorical value specifications. Its domain will be restricted to *obo:OBI_0001933* ('Value specification'), its range to *obo:OBI_0000963* ('Categorical label').

![rdfbones-o_data_categoricalvaluespecification](https://cloud.githubusercontent.com/assets/8103073/26304079/57012340-3eea-11e7-8492-464e62e57400.png)
**Figure:** Categorical value specifications, employing a newly introduced object property for referencing specified categorical labels (cf. [key to symbols in network graphs](https://github.com/RDFBones/RDFBones-O/wiki/Network-graph-legend)).

**Comment by jamesaoverton** [comment]
You're right that scalar and categorical value specifications can't work in quite the same way. "Handedness" might not be the best example. We've been doing recent work tumor grades. Input and contributions would be very welcome. https://github.com/obi-ontology/obi

**Comment by cuboideum** [comment]
@jamesaoverton: Thanks for your comment, we are still very interested in the issue. Where can we view the tumor-grades example and how can we participate?

**Comment by jamesaoverton** [comment]
Here are two relevant recent tracker items:

- https://github.com/obi-ontology/obi/issues/856
- https://github.com/obi-ontology/obi/issues/862

Our discussions tend to focus on a tracker item with specific needs, with much of the discussion on our Monday conference call. You are very welcome to open a new issue on the OBI tracker and attend the calls. Call details are at the bottom of our homepage: http://obi-ontology.org

**Comment by cuboideum** [comment]
See superordinate issue #123.

**Comment by cuboideum** [comment]
The OBI workgroup has issued a clarification on data modelling which also helps to understand categorical value specifications. See link in comment to https://github.com/RDFBones/RDFBones-O/issues/123#issuecomment-707086393.
