### ISSUE TITLE
Wiki: Some Anatomical elements miss page or are misleading

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#14]
e.g. https://github.com/RDFBones/RDFBones-O/wiki/Skeletal-region_Lower-limbs should show a list of bones associated with this region while another page named Low-limbs should contain this ontology information. Same with upper limbs.

The pages Shoulder-girdle, Vertebral-column Thoracic-bones with ontology info are missing completely.

@CarolinHachmann Please fix this mess!!

**Comment by cuboideum** [comment]
The page on lower limbs should provide information on the FMA and Galen classes that represent bone material from the lower limbs. The skeletal region pages linked from the anatomy model page are the only ones that were intended to be overview pages. But they should also be the only pages that have 'skeletal region' in the title. The page on lower limbs should just be called 'Lower-limbs'.

**Comment by zarquon42b** [comment]
Thank you very much.
