### ISSUE TITLE
Expanding combined skeletal segments/entire bone organ classes

### ISSUE THREAD

**Issue by 15E601** [RDFBones/RDFBones-O#142]
Some classes of combined skeletal elements needed for the Phaleron skeletal inventory. It has been suggested to put these classes into the RDFBones core ontology instead of the Phaleron extension. The following classes were suggested for the Phaleron extension, with class on the left and suggested parent class on the right:

Full skeleton, cranium, thorax, and sacrum:
phaleron-si:EntireCranium			rdfbones:CombinationOfSkeletalSegments
phaleron-si:EntireSkeleton			rdfbones:CombinationOfSkeletalSegments
phaleron-si:EntireSacrum      rdfbones:CombinationOfSkeletalSegments
phaleron-si:EntireThorax      rdfbones:CombinationOfSkeletalSegments

The hand and foot bones also require additional classes:
phaleron-si:EntireHand  rdfbones:CombinationOfSkeletalSegments
phaleron-si:EntireLeftHand  phaleron-si:EntireHand
phaleron-si:EntireRightHand phaleron-si:EntireHand
phaleron-si:EntireFoot  rdfbones:CombinationOfSkeletalSegments
phaleron-si:EntireLeftFoot  phaleron-si:EntireFoot
phaleron-si:EntireRightFoot phaleron-si:EntireFoot

These are more specific and probably find limited use outside of the Phaleron application, and perhaps should not be placed in the RDFBones core ontology:
phaleron-si:EntireLeftDistalPhalanx			rdfbones:EntireBoneOrgan_fma321958
phaleron-si:EntireRightDistalPhalanx			rdfbones:EntireBoneOrgan_fma321958
phaleron-si:EntireLeftMiddlePhalanx			rdfbones:EntireBoneOrgan_fma321957
phaleron-si:EntireRightMiddlePhalanx			rdfbones:EntireBoneOrgan_fma321957
phaleron-si:EntireLeftProximalPhalanx			rdfbones:EntireBoneOrgan_fma321956
phaleron-si:EntireRightProximalPhalanx			rdfbones:EntireBoneOrgan_fma321956

phaleron-si:EntireLeftDistalPhalanxOfFinger			rdfbones:EntireBoneOrgan_fma75818
phaleron-si:EntireRightDistalPhalanxOfFinger			rdfbones:EntireBoneOrgan_fma75818
phaleron-si:EntireLeftMiddlePhalanxOfFinger			rdfbones:EntireBoneOrgan_fma75817
phaleron-si:EntireRightMiddlePhalanxOfFinger			rdfbones:EntireBoneOrgan_fma75817
phaleron-si:EntireLeftProximalPhalanxOfFinger			rdfbones:EntireBoneOrgan_fma75816
phaleron-si:EntireRightProximalPhalanxOfFinger			rdfbones:EntireBoneOrgan_fma75816
phaleron-si:EntireLeftDistalPhalanxOfToe			rdfbones:EntireBoneOrgan_fma75830
phaleron-si:EntireRightDistalPhalanxOfToe			rdfbones:EntireBoneOrgan_fma75830
phaleron-si:EntireLeftMiddlePhalanxOfToe			rdfbones:EntireBoneOrgan_fma75829
phaleron-si:EntireRightMiddlePhalanxOfToe			rdfbones:EntireBoneOrgan_fma75829
phaleron-si:EntireLeftProximalPhalanxOfToe			rdfbones:EntireBoneOrgan_fma75828
phaleron-si:EntireRightProximalPhalanxOfToe			rdfbones:EntireBoneOrgan_fma75828

phaleron-si:EntireLeftPartOfCervicalVertebra			rdfbones:EntireBoneOrgan_fma9915
phaleron-si:EntireRightPartOfCervicalVertebra			rdfbones:EntireBoneOrgan_fma9915
phaleron-si:EntireBodyOfCervicalVertebra			rdfbones:EntireBoneOrgan_fma9915
phaleron-si:EntireLeftPartOfThoracicVertebra			rdfbones:EntireBoneOrgan_fma9139
phaleron-si:EntireRightPartOfThoracicVertebra			rdfbones:EntireBoneOrgan_fma9139
phaleron-si:EntireBodyOfThoracicVertebra			rdfbones:EntireBoneOrgan_fma9139
phaleron-si:EntireLeftPartOfLumbarVertebra			rdfbones:EntireBoneOrgan_fma9921
phaleron-si:EntireRightPartOfLumbarVertebra			rdfbones:EntireBoneOrgan_fma9921
phaleron-si:EntireBodyOfLumbarVertebra			rdfbones:EntireBoneOrgan_fma9921
phaleron-si:EntireNeuralArchOfVertebra			rdfbones:EntireBoneOrgan_fma9914
phaleron-si:EntireBodyOfVertebra			rdfbones:EntireBoneOrgan_fma9914

**Comment by cuboideum** [comment]
@15E601: I follow your suggestion to include the following classes in the RDFBones core ontology:

* phaleron-si:EntireCranium rdfbones:CombinationOfSkeletalSegments
* phaleron-si:EntireSkeleton rdfbones:CombinationOfSkeletalSegments
* phaleron-si:EntireSacrum rdfbones:CombinationOfSkeletalSegments
* phaleron-si:EntireThorax rdfbones:CombinationOfSkeletalSegments

* phaleron-si:EntireHand rdfbones:CombinationOfSkeletalSegments
* phaleron-si:EntireLeftHand phaleron-si:EntireHand
* phaleron-si:EntireRightHand phaleron-si:EntireHand
* phaleron-si:EntireFoot rdfbones:CombinationOfSkeletalSegments
* phaleron-si:EntireLeftFoot phaleron-si:EntireFoot
* phaleron-si:EntireRightFoot phaleron-si:EntireFoot

A pull request follows.

**Comment by cuboideum** [comment]
I suggest the following solution for implementing anatomical regions of interest referencing defined parts of the skeleton:

![RDFBones-AnatomicalRegionOfInterest](https://user-images.githubusercontent.com/8103073/128154935-42684fdb-747d-43ab-967f-1429c592fe07.png)

The class 'Entire set of bone organs' is a third major kind of anatomical regions of interest, in addition to 'Segment of skeletal element' and 'Combination of skeletal segments'. All subclasses are defined as regional parts of some subclass of 'Set of bone organs' (fma:71344).

This solution makes sure that our anatomical model mirrors the FMA. Instances of subclasses of 'Set of bone organs' are normally not needed and instantiation is only feasible if the association of a number of bones in such a set is evident from the material. This might, for instance, be the case with sacral vertebrae fused into a sacrum or with skeletons from corpses where the anatomical association is obvious.

**Comment by cuboideum** [comment]
Correction of [my previous post](https://github.com/RDFBones/RDFBones-O/issues/142?_pjax=%23repo-content-pjax-container#issuecomment-892513664):

![RDFBones-AnatomicalRegionOfInterest](https://user-images.githubusercontent.com/8103073/128166456-78b4df8e-87a9-405a-9857-ac4bd49271e8.png)

I have added the class 'Entire set of organs' to keep with the existing levels of anatomical detail.

**Comment by cuboideum** [comment]
Fixed by e33aff9 implementing the following classes:e33aff9

* 'Entire set of bones of skull' (requested as 'Entire cranium')
* 'Entire osseous skeleton' (requested as 'Entire skeleton')
* 'Entire set of sacral vertebrae' (requested as 'Entire sacrum')
* 'Entire set of all ribs' (requested as 'Entire thorax')
* 'Entire skeleton of hand' (requested as 'Entire hand')
* 'Entire skeleton of right hand' (requested as 'Entire right hand')
* 'Entire skeleton of left hand' (requested as 'Entire left hand')
* 'Entire skeleton of foot' (requested as 'Entire foot')
* 'Entire skeleton of right foot' (requested as 'Entire right foot')
* 'Entire skeleton of left foot' (requested as 'Entire left foot')
