### ISSUE TITLE
Missing Classes for EntirePrimary[Toothtype] / wrong classes referenced in graphics

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#152]
The classes listed below are lacking labels. Please add those.
 

- rdfbones:EntirePrimaryMolarTooth
- rdfbones:EntirePrimaryMaxillaryMolarTooth
- rdfbones:EntirePrimaryMandibularMolarTooth
- rdfbones:EntirePrimaryCanineTooth
- rdfbones:EntirePrimaryUpperCanineTooth
- rdfbones:EntirePrimaryLowerCanineTooth
- rdfbones:EntirePrimaryIncisorTooth
- rdfbones:EntirePrimaryUpperIncisorTooth
- rdfbones:EntirePrimaryLowerIncisorTooth

**Comment by zarquon42b** [comment]
It seems that none of the classes are present in the ontology. While the falseness of IRIs affects the correctness of the related network graph visualization, those teeth are missing from the core ontology.
Exceptions:  
(rdfbones:EntireTooth_fma84228) = rdfbones:EntirePrimaryUpperCanineTooth
(rdfbones:EntireTooth_fma84229) = rdfbones:EntirePrimaryLowerCanineTooth

**Comment by cuboideum** [comment]
Commit https://github.com/RDFBones/RDFBones-O/commit/8efe5eca877a2622696ef0c60b1e72824c8854d7 adds the missing classes to the core ontology.

**Comment by cuboideum** [comment]
Commit https://github.com/RDFBones/RDFBonesGraphics/commit/40347864baec2faa536156cdeb2b0c2bdc2c4119 corrects the erroneous class references in the 'ToothCrown' sheet of the [Phaleron dental inventory construction plan](https://github.com/RDFBones/RDFBonesGraphics/blob/main/NetworkGraphics/OntologyExtensions/phaleron-di/phaleron-di_NetworkGraphics.svg).

**Comment by cuboideum** [comment]
While this issue is resolved, please also note additional changes requested in issue #155.
