### ISSUE TITLE
[Phaleron-DentalPathologies] Missing Restriction on Alveolar Resorption for M3 in mandible 

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#156]
Section: `DentalPaleopathologyPermanentMandibularArcade` is missing Restriction on Alveolar Resorption for M3  ind mandible  for `http://w3id.org/rdfbones/core#EntireToothSocket_fma317396`

**Comment by 15E601** [comment]
Sorry, I don't follow. Where is this section? Is this about the template DI_Permanent_Mandibula? Everything looks fine.

**Comment by zarquon42b** [comment]
It's about the dental patho ontology. I tagged you accidentally, sorry!

**Comment by cuboideum** [comment]
Fixed by commit https://github.com/RDFBones/Phaleron-DentalPathologies/commit/d3300f03e0953327863752e76239f0f596696e87.

**Comment by cuboideum** [comment]
The Phaleron-AppOntology repository is updated so that these changes are reflected there.
