### ISSUE TITLE
[Phaleron-DentalInventory] Erroneous reference to non-existing label phaleron-patho:ImpossibilityOfObservation

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#158]
The file [Template_PhaleronDI-ValueSpecifications.tsv](https://github.com/RDFBones/Phaleron-DentalInventory/blob/robot/Template_PhaleronDI-ValueSpecifications.tsv) erroneously references the non-existing label `phaleron-patho:ImpossibilityOfObservation` eight times.

**Comment by cuboideum** [comment]
Fixed by commit https://github.com/RDFBones/Phaleron-DentalInventory/commit/3109adc4cdfebb2183ee1860b0eda59aaf490e1c.

**Comment by cuboideum** [comment]
The [Phaleron-AppOntology repository](https://github.com/AnthroGraph/Phaleron-AppOntology) is updated. The output of the [ROBOT script](https://github.com/AnthroGraph/Phaleron-AppOntology/blob/robot/Script_PhaleronApp-Robot.sh) now reflects the implemented changes.
