### ISSUE TITLE
Missing Sortinglabels in dentalwear

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#159]
The LabelSorting items are missing for
 `<http://w3id.org/rdfbones/ext/wearpatterns/LargeDentineAreaWithEnamelRimComplete>`
`<http://w3id.org/rdfbones/ext/dentalwear/QuadrantWornFlatNoDentineExposure>`

Code to find out values with missing sorting index:

```
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
             SELECT DISTINCT $value ?index WHERE {
             ?myclass  rdfs:subClassOf ?myRS1 .
              FILTER (?myclass IN (<http://w3id.org/rdfbones/ext/phaleron-di/WearOfIncisorsAndCaninesValueSpecification> , <http://w3id.org/rdfbones/ext/dentalwear/WearOfMolarsValueSpecification> ))
  			       
              ?myRS1 a owl:Restriction ;
                            <http://www.w3.org/2002/07/owl#onProperty> <http://purl.obolibrary.org/obo/OBI_0000999> ;
                            owl:someValuesFrom|owl:onClass ?selection .
  	    ?selection owl:oneOf/rdf:rest*/rdf:first ?value .
             FILTER(not exists {?index obo:IAO_0000136 ?value}) .	     
}  
```

**Comment by cuboideum** [comment]
The problem with the wearpatterns item lies here:

https://github.com/RDFBones/Phaleron-DentalInventory/blob/robot/Template_PhaleronDI-ValueSpecifications.tsv#L27

The referenced category label is misnamed as "wearpatterns:LargeDentineAreaWithEnamelRimComplet".

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-DentalInventory/commit/102df25cb363199f102b7f25ff0a92f08bceb59e.

**Comment by cuboideum** [comment]
@zarquon42b: The changes from commit https://github.com/RDFBones/Phaleron-DentalInventory/commit/102df25cb363199f102b7f25ff0a92f08bceb59e are also reflected in the robot branch of the RDFBones-AppOntology repository.
