### ISSUE TITLE
[RDFBones-Graphics] Replace ImpossibilityOfObservation with ObservationImpossible in Dental Patho 

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#161]
Replace ImpossibilityOfObservation with ObservationImpossible in Dental Patho Network Graphics.

**Comment by cuboideum** [comment]
Allready accomplished with commit https://github.com/RDFBones/RDFBonesGraphics/commit/fb07814b2e0adb86c2029d0895c893d25a8cd70b.
