### ISSUE TITLE
[Phaleron-Pathologies] Size & Shape: change is_about ROISpec to has_part

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#178]
Change is_about statement in SizeAndShape module assigning a ROISpecification to has_part to make consistent with other modules.
Here is the graph part I am referring to:
![Selection_161](https://user-images.githubusercontent.com/1515863/226332224-0a02dd97-22ca-4910-b512-047e5d0d90a9.png)

**Comment by cuboideum** [comment]
Changed building plan with commit https://github.com/RDFBones/RDFBonesGraphics/commit/6f9f2861fbfdf6988df7c6b819c35658b67d807f.

**Comment by cuboideum** [comment]
Changes to Phaleron-Pathologies ontology extension are incorporated into pull request https://github.com/RDFBones/Phaleron-Pathologies/pull/11.

**Comment by cuboideum** [comment]
Fixed with pull request https://github.com/RDFBones/Phaleron-Pathologies/pull/11.

**Comment by cuboideum** [comment]
The [Phaleron App Ontology](https://github.com/AnthroGraph/Phaleron-AppOntology) has been updated with commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/4e78c4290a9e7bd7856188e46e20178fb2504a85.
