### ISSUE TITLE
[Phaleron-Pathologies] Size & Shape: constraint to number of available ROIs instead of specific types

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#179]
To make the constraint query feasible for SPARQL, I would suggest to constrain it to a minimum number of ROIs that have to be present instead of very specific configurations.

**Comment by cuboideum** [comment]
Construction plan changed to require five ROIs to be scored other than 'missing' in commit https://github.com/RDFBones/RDFBonesGraphics/commit/c5552409f3d3e2cec72de71b769679ef1dfa7971.

**Comment by cuboideum** [comment]
Fixed with pull request https://github.com/RDFBones/Phaleron-Pathologies/pull/11.

**Comment by cuboideum** [comment]
Phaleron App Ontology has been updated with commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/4e78c4290a9e7bd7856188e46e20178fb2504a85.
