### ISSUE TITLE
[RDFBonesGraphics] Netwrok Graphics Non-metric traits issues

### ISSUE THREAD

**Issue by zarquon42b** [RDFBones/RDFBones-O#181]
The graphics for non-metric traits contains the following issues:

1. `ObservationOfSkullSizeAndShape` => `ObservationOfNonMetricTraitsAndAnomalies`
2. Missing "is_about" statement regarding ROI instance from phaleron-app (e.g. `PhaleronOsCoxaeROIs`)
3. unclear what the current "is_about" statement references.

**Comment by cuboideum** [comment]
The meaning of the current 'is about' statements becomes clear through the addition of references to a ROI group: Several ROIs referenced by the respective group can be selected.
