### ISSUE TITLE
Inconsistent/incoherent use of standards-patho vs phaleron-patho namespaces in osteopathology module

### ISSUE THREAD

**Issue by 15E601** [RDFBones/RDFBones-O#192]
The osteopaleopath module saves measurement data of the type 'Activity of pathological process' under the IRI
`phaleron-patho/ActivityOfPathologicalProcess`. This class does not exist in the ontology, where it is instead
`standards-patho/ActivityOfPathologicalProcess`

![image](https://github.com/RDFBones/RDFBones-O/assets/67172847/a4816409-bb05-43c9-a525-1a0ebb39ef4a)

As with issue AnthroGraph/PBP-App#65, this means we have this error saved in all current osteopatho graphs. It also makes my csv export query produce confusing outputs, as the faulty MD class of course has no label, meaning no item appears in the output.

I presume this and `EndostealSurfaceBoneFormationCharacteristics` are the only classes with this issue since I do not see any further faulty results in the export, but I may have missed something.

**Comment by cuboideum** [comment]
@15E601: I do not quite see how this can be fixed in the ontology. Shouldn't the issue be filed with the PBP app?

**Comment by 15E601** [comment]
This would have required an ontology fix if the intended class had the phaleron-patho prefix. I gather that the standards-patho prefix is intended, therefore this is indeed a PBP-app issue
