### ISSUE TITLE
Aufnahmebögen Diskretia

### ISSUE THREAD

**Issue by kdaveed** [RDFBones/RDFBones-O#34]
This issue proposes a possible interpretation of an interface to store the information of the _Diskreta_ check list (Aufnahmenbögen).
On the check list there are all tokens (Merkmale) are listed grouped by the bones of the skull. For the Frontal bone the table looks like this : 

![screen shot 2016-05-08 at 09 27 48](https://cloud.githubusercontent.com/assets/7580884/15096571/285b6aa2-14ff-11e6-8ccb-b1ab29d211f4.png)

After the token, the researcher has to write a code values from the following table :

![screen shot 2016-05-08 at 09 25 19](https://cloud.githubusercontent.com/assets/7580884/15096563/d1f463da-14fe-11e6-9870-f4f5091dbf41.png)

Now the question how can we model the check list, so that an application can be built. As the left and right bones are addressed in the ontology distinctly, then my suggestion that we should store the tokens as well distinctly. The distinct addressing means, that if we have skull, whose bones are loaded to the database, then the left and the right ones of each bone type are represented by different RDF instances. Thus to each existing instance we can assign information about its token.

In the key list we can find 2 features, the _present_ and the _observable_. This means that we have 4 possibilities, but I recommend to restrict them to the following three : 
* Present and observable
* Present and not observable 
* Not present

because the the _Not present and not observable_ option would not make a lot of sense, since if we do not have something we do not see it. So my recommendation for the interface looks like this : 

![screen shot 2016-05-08 at 10 14 51](https://cloud.githubusercontent.com/assets/7580884/15096711/c7c7867e-1505-11e6-8abb-cb0b2207b918.png)

And the ontology behind this would look like this : 

![screen shot 2016-05-08 at 10 27 37](https://cloud.githubusercontent.com/assets/7580884/15096777/877789a0-1507-11e6-996d-80ed516ae5c0.png)

Carolin, please try to make considerations about the other type of forms till Tuesday so that we may discuss them.

**Comment by cuboideum** [comment]
The skeletal markers that are referred to as 'Diskreta' will be entered by means of an extension. The design of this extension will have to follow the general rules how to build them, respecting the structures defined by the OBI. This is the core interest of this project and we will not discuss other means of implementing them.
