### ISSUE TITLE
OBO namespace and FMA properties

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBones-O#41]
With the OBO subset of the FMA, there are different naming conventions for classes and properties. The convention for properties involves a '#' and is consequently interpreted as a different namespace by VIVO.

Find a way to have the FMA properties being listed under the OBO namespace.

**Comment by zarquon42b** [comment]
This is to be solved by creating a new namespace for the properties. Unfortunately, there are no nested namespaces in RDF/XML.
