### ISSUE TITLE
Spelling Mistake Coxxyx

### ISSUE THREAD

**Issue by kdaveed** [RDFBones/RDFBones-O#44]
As I was looking for the class in Protege, and I did not find _Coxxyx_ just _Coccyx_. I corrected it on the [wiki page](https://github.com/RDFBones/RDFBones-O/wiki/Skeletal-region_vertebral-column). Please check it and reply if the correction was unnecessary.

**Comment by cuboideum** [comment]
Your observation is correct, thanks for the correction.
