### ISSUE TITLE
Primary skeletal inventory for teeth

### ISSUE THREAD

**Issue by cuboideum** [RDFBones/RDFBones-O#46]
Create a primary skeletal inventory for teeth.

**Comment by cuboideum** [comment]
The following list contains the FMA classes that might be relevant for constructing primary skeletal inventories for teeth (formatting according to wiki page [Anatomical model](https://github.com/RDFBones/RDFBones-O/wiki/Anatomical-model)):

* __obo:FMA_75151 ('Primary dentition')__
   * _**obo:FMA_55634 ('Maxillary dental arcade')**_
      * obo:FMA_84236 ('Upper second primary molar tooth')
      * obo:FMA_84211 ('Upper first primary molar tooth')
      * obo:FMA_84230 ('Right upper primary canine tooth')
      * obo:FMA_84222 ('Right upper lateral primary incisor tooth')
      * obo:FMA_84220 ('Right upper central primary incisor tooth')
      * obo:FMA_84221 ('Left upper central primary incisor tooth')
      * obo:FMA_84223 ('Left upper lateral primary incisor tooth')
      * obo:FMA_84231 ('Left upper primary canine tooth')
      * obo:FMA_84239 ('Left upper first primary molar tooth')
      * obo:FMA_84241 ('Left upper second primary molar tooth')
   * _**obo:FMA_55635 ('Mandibular dental arcade')**_
      * obo:FMA_84245 ('Left lower second primary molar tooth')
      * obo:FMA_84243 ('Left lower first primary molar tooth')
      * obo:FMA_84233 ('Left lower primary canine tooth')
      * obo:FMA_84227 ('Left lower lateral primary incisor tooth')
      * obo:FMA_84225 ('Left lower central primary incisor tooth')
      * obo:FMA_84224 ('Right lower central primary incisor tooth')
      * obo:FMA_84226 ('Right lower lateral primary incisor tooth')
      * obo:FMA_84232 ('Right lower primary canine tooth')
      * obo:FMA_84242 ('Right lower first primary molar tooth')
      * obo:FMA_84244 ('Right lower second primary molar tooth')

* __obo:FMA_75152 ('Secondary dentition')__
   * _**obo:FMA_55634 ('Maxillary dental arcade')**_
      * obo:FMA_55696 ('Right upper third secondary molar tooth')
      * obo:FMA_55697 ('Right upper second secondary molar tooth')
      * obo:FMA_55698 ('Right upper first secondary molar tooth')
      * obo:FMA_55688 ('Right upper second secondary premolar tooth')
      * obo:FMA_55689 ('Right upper first secondary premolar tooth')
      * obo:FMA_55798 ('Right upper secondary canine tooth')
      * obo:FMA_55680 ('Right upper lateral secondary incisor tooth')
      * obo:FMA_55681 ('Right upper central secondary incisor tooth')
      * obo:FMA_55682 ('Left upper central secondary incisor tooth')
      * obo:FMA_55683 ('Left upper lateral secondary incisor tooth')
      * obo:FMA_55799 ('Left upper secondary canine tooth')
      * obo:FMA_55690 ('Left upper first secondary premolar tooth')
      * obo:FMA_55699 ('Left upper first secondary molar tooth')
      * obo:FMA_55700 ('Left upper second secondary molar tooth')
      * obo:FMA_55701 ('Left upper third secondary molar tooth')
   * _**obo:FMA_55635 ('Mandibular dental arcade')**_
      * obo:FMA_55702 ('Left lower third secondary molar tooth')
      * obo:FMA_55703 ('Left lower second secondary molar tooth')
      * obo:FMA_55704 ('Left lower first secondary molar tooth')
      * obo:FMA_55692 ('Left lower second secondary premolar tooth')
      * obo:FMA_55693 ('Left lower first secondary premolar tooth')
      * obo:FMA_55687 ('Left lower secondary canine tooth')
      * obo:FMA_57141 ('Left lower lateral secondary incisor tooth')
      * obo:FMA_57143 ('Left lower central secondary incisor tooth')
      * obo:FMA_57142 ('Right lower central secondary incisor tooth')
      * obo:FMA_57140 ('Right lower lateral secondary incisor tooth')
      * obo:FMA_55686 ('Right lower secondary canine tooth')
      * obo:FMA_55694 ('Right lower first secondary premolar tooth')
      * obo:FMA_55695 ('Right lower second secondary premolar tooth')
      * obo:FMA_55705 ('Right lower first secondary molar tooth')
      * obo:FMA_55706 ('Right lower second secondary molar tooth')
      * obo:FMA_55707 ('Right lower third secondary molar tooth')

---

* _**obo:FMA_75150 ('Dentition')**_
   * _**obo:FMA_59415 ('Dental arcade')**_
      * _obo:FMA_12516 ('Tooth')_
      * _obo:FMA_55655 ('Primary tooth')_
      * _obo:FMA_55654 ('Secondary tooth')_
      * _obo:FMA_12823 ('Incisor tooth')_
      * _obo:FMA_84200 ('Primary incisor tooth')_
      * _obo:FMA_84214 ('Upper primary incisor tooth')_
      * _obo:FMA_84217 ('Upper lateral primary incisor tooth')_
      * _obo:FMA_84216 ('Upper central primary incisor tooth')_
      * _obo:FMA_84215 ('Lower primary incisor tooth')_
      * _obo:FMA_84218 ('Lower central primary incisor tooth')_
      * _obo:FMA_84219 ('Lower lateral primary incisor tooth')_
      * _obo:FMA_84201 ('Secondary incisor tooth')_
      * _obo:FMA_55712 ('Upper secondary incisor tooth')_
      * _obo:FMA_55722 ('Upper central secondary incisor tooth')_
      * _obo:FMA_55724 ('Upper lateral secondary incisor tooth')
      * _obo:FMA_55713 ('Lower secondary incisor tooth')_
      * _obo:FMA_55723 ('Lower central secondary incisor tooth')_
      * _obo:FMA_55725 ('Lower lateral secondary incisor tooth')_
      * _obo:FMA_55636 ('Canine tooth')_
      * _obo:FMA_84202 ('Primary canine tooth')_
      * _obo:FMA_84228 ('Upper primary canine tooth')_
      * _obo:FMA_84229 ('Lower primary canine tooth')_
      * _obo:FMA_55637 ('Premolar tooth')_
      * _obo:FMA_55716 ('Upper secondary premolar tooth')_
      * _obo:FMA_55801 ('Upper first secondary premolar tooth')_
      * _obo:FMA_55802 ('Upper second secondary premolar tooth')_
      * _obo:FMA_55717 ('Lower secondary premolar tooth')_
      * _obo:FMA_55803 ('Lower first secondary premolar tooth')_
      * _obo:FMA_55804 ('Lower second secondary premolar tooth')_
      * _obo:FMA_55638 ('Molar tooth')_
      * _obo:FMA_84206 ('Primary molar tooth')_
      * _obo:FMA_84210 ('Upper primary molar tooth')_
      * _obo:FMA_84211 ('Upper first primary molar tooth')_
      * _obo:FMA_84236 ('Upper second primary molar tooth')_
      * _obo:FMA_84213 ('Lower primary molar tooth')_
      * _obo:FMA_84212 ('Lower first primary molar tooth')_
      * _obo:FMA_84237 ('Lower second primary molar tooth')_
      * _obo:FMA_84207 ('Secondary molar tooth')_
      * _obo:FMA_55720 ('Upper secondary molar tooth')_
      * _obo:FMA_55811 ('Upper first secondary molar tooth')_
      * _obo:FMA_55812 ('Upper second secondary molar tooth')_
      * _obo:FMA_55813 ('Upper third secondary molar tooth')_
      * _obo:FMA_55721 ('Lower secondary molar tooth')_
      * _obo:FMA_55814 ('Lower first secondary molar tooth')_
      * _obo:FMA_55815 ('Lower second secondary molar tooth')_
      * _obo:FMA_55817 ('Lower third secondary molar tooth')_

Teeth are more complicated than other skeletal regions, as there are two sets: the primary dentition (milk teeth) and the secondary dentition (permanent teeth). The transition from primary to secondary dentition is gradual, to the effect that only very young children have a complete primary dentition. Most children and juveniles have a mixed dentition that cannot be described as either primary or secondary. Therefore, I would suggest not to incorporate the classes obo:FMA_75151 ('Primary dentition') and obo:FMA_75152 ('Secondary dentition'), but to relate all teeth to instances of class obo:FMA_75150 ('Dentition'). From the contained theeth it is easy to judge to what degree a dentition is primary or secondary.

There are a lot of general classes that can be used for addressing teeth that cannot be classified exactly. I do not have the practical experience of working with teeth to judge which of these might be most in demand. Therefore, it might be best to include them all, though selection might be tedious for the user.

**Comment by cuboideum** [comment]
The FMA does not address supernumerary teeth in cases of hyperdontia. For the inventory, it would make sense to create a specific class for supernumerary teeth. Simply adding another instance of class obo:FMA_12516 ('Tooth') would not suffice, as it cannot be discerned whether this was a non-classified regular or a supernumerary tooth.

We need to decide if we want to provide a mechanism for locating supernumerary teeth in the dental arcade or if we want to leave this to extension developers. Personally, I would opt for the latter. There seem to be systems for numbering supernumerary teeth (cf. a [dedicated blog entry](http://supernumeraryteeth.com/category/supernumerary-teeth-facts/)).

To account for missing teeth in cases of hypodontia, the primary inventory should have a completeness datum offering an option to label tooth positions as congenitally missing teeth (cmt, cf. [article in the Dental Research Journal](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4336964/)).

**Comment by cuboideum** [comment]
In the project meeting on 10 January 2017, it was decided that the primary tooth inventory should contain the concept of tooth positions. Both a tooth and its corresponding socket are systemic parts of the tooth position. Information like teeth not being realised in a dentition can be linked to the position, information like teeth being found in their sockets or not to the tooth, information like antemortem tooth loss to the socket.

Tooth positions are not addressed in the FMA, so the concept has to be introduced by the RDFBones ontology.

**Comment by cuboideum** [comment]
This is another improvement that we discussed and agreed upon in the project meeting of 7 March 2017.

First, I introduced the concept of a 'region of interest'. This might not just be of interest in connection with skeletal inventories but also in other contexts.

[RDFBones-O_RegionOfInterest.pdf](https://github.com/RDFBones/RDFBones-O/files/893153/RDFBones-O_RegionOfInterest.pdf)

Both segments of skeletal elements (e.g. bone segments) and a yet to be created superclass for tooth positions (:CombinationOfSkeletalSegments) are such regions of interest. All measurement data in skeletal inventories need to refer to some region of interest. So the final structure of the  tooth inventory is this:

[RDFBones-O_PrimarySkeletalInventory.pdf](https://github.com/RDFBones/RDFBones-O/files/893169/RDFBones-O_PrimarySkeletalInventory.pdf)

**Comment by cuboideum** [comment]
Sorry, my draft of 4 April does not make sense. If a tooth position is not expressed, it has neither tooth nor tooth socket as part. As a consequence, the non-expressed tooth position is not linked to any other skeletal element or feature, namely a jaw bone. So this will not work for us.

In order to find a better solution, I have looked at the FMA again and developed a new concept of how the skeleton of the mouth is represented there. In case you wonder why I can come up with several of such concepts: the FMA is rather complex and there are enough classes to model anatomical concepts in various ways. In the following draft, black lines represent explicit restrictions in the FMA, while grey lines represent restrictions that I had to add but which are analogous to other explicit restrictions.

![rdfbones-o_dentalsystemfma](https://cloud.githubusercontent.com/assets/8103073/26048633/3fe57658-3958-11e7-82d2-d69b2f624a32.png)

Our tooth position is composed of a tooth and a socket, i.e. parts of a dental arcade and an alveolar arch. So, it would make more sense to link it to these superordinate classes than to the individual items that would not be there if the position was not expressed. However, it would be even more elegant to link the position to a jaw, implying its impact on both alveolar arch and dental arcade:

![rdfbones-o_dentalsystemrdfbones-o](https://cloud.githubusercontent.com/assets/8103073/26048855/20e9a3fe-3959-11e7-9ba4-61148a0a8180.png)

Applied to the RDFBones primary dental inventory, this would imply the following:

![rdfbones-o_primarydentalinventorytoothpositions](https://cloud.githubusercontent.com/assets/8103073/26049476/70555468-395b-11e7-9648-cec06c52aced.png)

This is a rather complex structure and I wonder if we should drop tooth positions from the primary inventory and just record teeth and tooth sockets instead, leaving the assessment of hypodontia to specialised inventories:

![rdfbones-o_primarydentalinventoryminimaldraft](https://cloud.githubusercontent.com/assets/8103073/26049540/a79471a2-395b-11e7-92fd-30814ade52e3.png)

Here, the class _obo:FMA\_5018 ('Bone organ')_ stands for either a mandible or a maxilla. Here primary dental inventories link up with primary skeletal inventories recording bones.

What do you think, is the recording of tooth positions vital to primary skeletal inventories?

**Comment by MasterChief13** [comment]
You are right that is is better to relate teeth to the jaw bones. In this way, dental and skeletal inventories are closely linked to each other.

Concerning you question whether or not to implement the concept of tooth positions: I think it is best to answer your question by stating what you can and what you cannot do with a primary dental inventory _without implementing tooth positions_.
You can record if the whole jaw is preserved, if teeth are present in their tooth sockets, if it is a primary or secondary tooth and if teeth were lost postmortally.
But you cannot decide whether a tooth was lost intravitally or if it is a case of hypodontia (there is simply no tooth or tooth socket). You cannot state if a tooth is erupted, partially erupted and so on (relevant for age estimation). And you cannot record if there is a primary _and_ secondary tooth at the same tooth position (mixed dentition).

To sum up, a primary dental inventory is good enough in most of the cases. For future development, a secondary dental inventory which is capable of handling special cases is necessary, though. But since we do not know how to create secondary inventories at the moment I prefer a solution without tooth positions - for the sake of simplicity and feasibility. 

A comment on the usage of restrictions. Will you define for each Tooth.X that is is contained in exactly one ToothPosition.X? For example, _EntireUpperRightCaninus 'is contained in'_ exactly one _EntireUpperRightCaninusToothSocket_. In this case, the qualified cardinality restriction requires that each instance of tooth is related to an instance of tooth socket (necessary condition). This is problematic in case that you have an isolated tooth but no jaw. Maybe we should use all-values-from restrictions to avoid this necessary condition.

**Comment by cuboideum** [comment]
@MasterChief13 

> I think it is best to answer your question by stating what you can and what you cannot do with a primary dental inventory without implementing tooth positions.

The main problem with a primary dental inventory without tooth positions is the automatic creation of triples for a complete dentition (or a complete lower or upper dental arcade). If clicking 'complete dentition' in the GUI results in creating 32 instances of teeth and sockets, this would not be correct in a case of hypodontia. If tooth positions were not implemented, user would have to be aware of this and remove the missing elements manually. Or they should not be given the opportunity to enter complete dentitions in the first place.

> Will you define for each Tooth.X that is is contained in exactly one ToothPosition.X?

Sorry, I did not comment on this, as it was not directly related to the tooth position problem. No, the 'is contained in' property is exclusively used to indicate that a tooth is preserved within a jaw bone. So the usage would be similar to parietal bones with a closed sagittal suture belonging to the same viscerocranium in a primary inventory for bones.

Actually, since the introduction of 'dental arcade' and 'alveolar arch' we do no longer need the 'is contained in' property. If the tooth is contained in the jaw, it is part of the respective dental arcade.

**Comment by MasterChief13** [comment]
I think that it is best to allow users to add a complete dentition. If I had to enter data from a human skull which has 28 teeth, I would prefer to press 'add all' and then remove the ones which are missing instead of adding 28 teeth by hand! Carolin would be happy about this opportunity, I assume. 
The 'add all' button shall make your life easier - it is just a heuristic and there will be some exceptional cases, of course. As a user I would understand the limitations of an 'add all' button.
