### ISSUE TITLE
Object property relations automatically defined by software

### ISSUE THREAD

**Issue by MasterChief13** [RDFBones/RDFBones-O#73]
At the moment I am working on an extension for RDFBones-O and want to implement the planning phase. In your wiki I found some network graphs showing blue object property relations that should be "automatically defined by software" (according to your "key to symbols in networt graphs"). What does that mean?
For the sake of simplicity, let's assume we have two classes "A" and "B" which are related to each other by the binary relation "r":  "A r B". I add instances of "A" and "B", "a" and "b" respectively. Can I then use the reasoner of Protégé to automatically compute "a r b"? How? Or is this a specific feature of your software RDFBones-O? Or must I create the object property for each pair of instances manually?

**Comment by cuboideum** [comment]
No, software, in this context, just refers to applications implementing the RDFBones ongology, e.g. the RDFBones application. Commit b23e1ae071fad10b95ef1ee8cdfed6b930c5aa5c in RDFBones-O.wiki fixes this issue by stating that blue relations are created by the RDFBones application. I assume, in this context it would be too specific to point out that the ontology is designed for implementation in all kinds of software applications.
