### ISSUE TITLE
Reasoner Error

### ISSUE THREAD

**Issue by kdaveed** [RDFBones/RDFBones-O#94]
The reasoner in VIVO gives the following error msg: 

org.semanticweb.owlapi.reasoner.ReasonerInternalException: Non simple role used as simple: http://purl.obolibrary.org/obo/BFO_0000050

if the RDFBones.owl contains restriction on the property : http://purl.obolibrary.org/obo/BFO_0000050.

**Comment by zarquon42b** [comment]
Can you upload a screenshot of the error? Can you access the VIVO UI?

**Comment by cuboideum** [comment]
@kdaveed Can you also paste the relevant lines from the logfile, please?

**Comment by kdaveed** [comment]
__This is the only one line regarding the reasoner error in the log file:__

_[JFactTBoxReasoner] org.semanticweb.owlapi.reasoner.ReasonerInternalException: Non simple role used as simple: http://purl.obolibrary.org/obo/BFO_0000050_

__And the screenshot:__ 

![screen shot 2016-12-15 at 13 42 30](https://cloud.githubusercontent.com/assets/7580884/21224442/8a7913f8-c2cc-11e6-8d96-ccb9443e7b7b.png)

**Comment by kdaveed** [comment]
It is strange because the other properties in the restrictions do not cause exceptions. Also if the restrictions on the property _http://purl.obolibrary.org/obo/BFO_0000050_ are commented out then it works.

**Comment by zarquon42b** [comment]
Commented in which file?

**Comment by kdaveed** [comment]
In the RDFBones.owl

**Comment by cuboideum** [comment]
There are three simple restrictions on obo:BFO_0000050 in RDFBones-O.owl:

```xml
<owl:Class rdf:about="http://w3id.org/rdfbones/core#SkeletalMaterialRequirement">
   <rdfs:subClassOf>
      <owl:Restriction>
         <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
         <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/OBI_0001896"/>
      </owl:Restriction>
   </rdfs:subClassOf>
</owl:Class>

<owl:Class rdf:about="http://w3id.org/rdfbones/core#SkeletalMaterialSpecification">
   <rdfs:subClassOf>
      <owl:Restriction>
         <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
         <owl:allValuesFrom rdf:resource="http://purl.obolibrary.org/obo/OBI_0000260"/>
      </owl:Restriction>
   </rdfs:subClassOf>
   <rdfs:subClassOf>
      <owl:Restriction>
         <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
         <owl:cardinality rdf:datatype="http://www.w3.org2001/XMLSchema#nonNegativeInteger">1</owl:cardinality>
      </owl:Restriction>
   </rdfs:subClassOf>
</owl:Class>
```
@kdaveed Did you comment them all out? It would be great if you could try them out separately in order to narrow down the problem.

**Comment by kdaveed** [comment]
Yes I commented out all of them. Okay, then I try them separately.

**Comment by zarquon42b** [comment]
This seems to be owed to the cardinality constraint (see http://protege-project.136.n4.nabble.com/Dead-reasoner-td4656114.html)

**Comment by zarquon42b** [comment]
@cuboideum will release a fix in a moment

**Comment by zarquon42b** [comment]
BTW: it works by removing the cardinality constraint only: RDFBones.owl, line 28594.

**Comment by kdaveed** [comment]
@zarquon42b, @cuboideum I experienced the same. The problem lies on the following restriction: 
```RDF
<owl:Restriction>
         <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
         <owl:cardinality rdf:datatype="http://www.w3.org2001/XMLSchema#nonNegativeInteger">1</owl:cardinality>
</owl:Restriction>
```

**Comment by zarquon42b** [comment]
Yes, that was what my previous messages intended to say.
