### ISSUE TITLE
Class group assignments

### ISSUE THREAD

**Issue by kdaveed** [RDFBones/RDFBones-O#97]
From the FrSexEst repository the file ClassGroupAssignment.owl has disappeared. Where are the class group assignments are defined right now?

**Comment by MasterChief13** [comment]
For the RDFBones-Workshop, zarquon42b wrote a classgroup assignment file. It was uploaded in the dirty-hacks-workshop branch. After the workshop I didn't merge the dirty-hacks branch but continued to work in my own branch so the file has never been added to the master branch. As I am not sure if the classgroup assignment file is ready for merge, I assigned zarquon42b to this issue.

**Comment by zarquon42b** [comment]
@kdaveed : This is what I was talking to you for the last months: what do you need/expect from the extensions to deliver? Do you rely on the classgroup assignements? Should I create that file?

**Comment by zarquon42b** [comment]
@kdaveed : Also, in your current branch investigationClean, the definition of http://vivoweb.org/ontology#vitroClassGroupAuxiliaries is missing in applicationMetadata/firsttime/RDFBonesClassgroups.rdf, that would be needed to set it up properly. This is the cause why I tried (in vain) to force you to test on clean systems!!! Please sit down, take a piece of paper (or a text editor) and write down all the additonal requirements that are needed, both on VIVO side as well as on the extension side to allow extensions to work. 
Also there are two types of class groups: vitroClassGroupInvestigations and vitroClassGroupAuxiliaries. Which of those do you need?

**Comment by kdaveed** [comment]
@zarquon42b, @MasterChief13 
> This is what I was talking to you for the last months: what do you need/expect from the extensions to deliver? Do you rely on the classgroup assignements? Should I create that file?

The only instance I would like to create from the admin panel is the instance of the __http://w3id.org/rdfbones/extensions/FrSexEst#Investigation.FrSexEst__  class. Therefore the only class group assignment needed is the following :

```
  <rdf:Description rdf:about="http://w3id.org/rdfbones/extensions/FrSexEst#Investigation.FrSexEst">
    <vitro:inClassGroup rdf:resource="http://vivoweb.org/ontology#vitroClassGroupInvestigations"/>
  </rdf:Description>
```
So the selector list looks like this: 
 
![screen shot 2016-12-20 at 13 48 31](https://cloud.githubusercontent.com/assets/7580884/21351066/10282b82-c6bb-11e6-88b1-d3144e9f2485.png)

**Comment by zarquon42b** [comment]
@kdaveed thanks for the clarification. Ah, I see. So on the VIVO side everything is set up correctly. This means every extension needs an appropriate statement (as mentioned above).
@MasterChief13 : can you add this to the wiki please?

**Comment by MasterChief13** [comment]
@zarquon42b I added this point to the page "General tips for extension writing" of the FrSexEst wiki
@kdaveed Can you open a pull request to FrSexEst containing the relevant class group assignment?

**Comment by kdaveed** [comment]
@zarquon42b  
Important that the initial classes such as investigations, skeletal inventories are assigned to the class groups to be able add them. The instances of other classes like specimen, bone segments, etc.. are added through custom entry forms.
@MasterChief13 Yes, I create the file and make the pull request.

**Comment by zarquon42b** [comment]
OK, then all is fine. Sorry for my somewhat harsh initial response.

**Comment by kdaveed** [comment]
@zarquon42b @MasterChief13 
This is okay. Could you give me permission to the FrSexEst repository so that I could push the class group file?

**Comment by zarquon42b** [comment]
Just open a pull request and I will merge it.

**Comment by kdaveed** [comment]
The problem that I could not push the file. Do I have to get access to the repository?

**Comment by zarquon42b** [comment]
Yes, that is why you do a pull request (from a fork). http://lmgtfy.com/?q=github+pull+request+workflow

**Comment by kdaveed** [comment]
Without pushing the branch I do not see how can we create pull request.
I get the following error msg when I try to push:
```
remote: Permission to RDFBones/FrSexEst.git denied to kdaveed.
fatal: unable to access 'https://github.com/RDFBones/FrSexEst.git/': The requested URL returned error: 403
```

Based on this forum entry (http://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed)

I set the following remote url : 
```
git remote set-url origin https://kdaveed@github.com/user/RDFBones/FrSexEst.git
```
But it did not work...
```
fatal: 'remote' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
Any idea?

**Comment by zarquon42b** [comment]
Did you actually read the instructions? You need to create a fork commit the changes in a feature branch and then request a pull request to this repo.

**Comment by kdaveed** [comment]
Now it is clear. The problem was that I just cloned the repo, not forked. The pull request has been created.
